# Generated by Django 3.1.5 on 2021-03-05 07:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('menumakerapp', '0002_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='variety',
            new_name='Cuisine',
        ),
    ]
