# Generated by Django 3.1.5 on 2021-03-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menumakerapp', '0003_auto_20210305_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
