# Generated by Django 3.1.5 on 2021-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menumakerapp', '0004_customadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objuser', models.CharField(max_length=30)),
                ('objcount', models.IntegerField()),
                ('objlist', models.CharField(max_length=255)),
            ],
        ),
    ]
